name: Deploy Migrator [Goerli]

on:
  workflow_dispatch:
    inputs:
      deployer_address:
        description: WalletConnect address to deploy from
        required: true
      migrator_version:
        type: choice
        description: Migrator version to deploy
        options:
          - v1
          - v2

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Deploy Migrator [Goerli]
    runs-on: ubuntu-latest
    steps:
      - name: Start Seacrest
        uses: hayesgm/seacrest@v1
        with:
          ethereum_url: "${{ secrets.ETH_GOERLI_URL }}"

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes

      - name: Forge Deploy Compound v2 Migrator [Goerli]
        env:
          ETHERSCAN_API_KEY: "${{ secrets.ETHERSCAN_API_KEY }}"
          ETH_FROM: "${{ inputs.deployer_address }}"
          MIGRATOR_VERSION: "${{ inputs.migrator_version }}"
          RPC_URL: "http://localhost:8585"
        run: |
          case $MIGRATOR_VERSION in
          v1) script/goerli/deploy_migrator.sh ;;
          v2) script/goerli/deploy_migrator_v2.sh ;;
          *) echo "Invalid option!" && exit 1 ;;
          esac
